/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import Conector.Conector;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jesús Ernesto
 */
public class FiltroPedidos extends javax.swing.JFrame {
    ArrayList f1,f2,finalf;
    TableRowSorter filtroAnd;
    public String nombre,fecha,total,abono,folio,concepto;
    int row;
    Vector<String> cols;
    public static String clase_procedencia;
    
    private static FiltroPedidos instancia=null;
    public static FiltroPedidos getInstance(){
        if(instancia==null){
            instancia=new FiltroPedidos();
        }
        return instancia;
    }
    /**
     * Creates new form FiltroPedidos
     */
    public FiltroPedidos() {
        cols=new Vector<String>();
        cols.add("Folio");
        cols.add("Fecha");
        cols.add("Nombre");
        cols.add("Concepto");
        cols.add("Abonado");
        cols.add("Total");
        cols.add("Telefono");
        initComponents();
        filtroAnd=new TableRowSorter();
        Filtro.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                checarFiltros();
            }
        
        });
        FechaInicial.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                checarFiltros();
            }
        
        });
        FechaFinal.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                checarFiltros();
            }
        
        });
    }
    void checarFiltros(){
        String cadena = Filtro.getText();
        Filtro.setText(cadena);
        repaint();
        FechaInicial.setEditable(ChekFecha.isSelected());
        FechaFinal.setEditable(ChekFecha.isSelected());
        if(ChekFecha.isSelected())
            filtroMixto();
        else
            filtroSolo();
        TablaFilPedidos.setRowSorter(filtroAnd); 
    }
    public void filtroSolo() {
        filtroAnd = new TableRowSorter(TablaFilPedidos.getModel());
        filtroAnd.setRowFilter(RowFilter.regexFilter("(?i)"+Filtro.getText()));
    }
    public void filtroMixto(){
        filtroAnd = new TableRowSorter(TablaFilPedidos.getModel());
        String x1=FechaInicial.getText();
        String x2=FechaFinal.getText();
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date fecha1 = new Date();
        Date fecha2 = new Date();
        try {
            fecha1 = format.parse(x1);
            fecha2 = format.parse(x2);
            
        } catch (ParseException ex) {
            ex.printStackTrace();
            }
        f1=new ArrayList();
        f2=new ArrayList();
        finalf=new ArrayList();
        f1.add(RowFilter.dateFilter(RowFilter.ComparisonType.EQUAL, fecha1,0));
        f1.add(RowFilter.dateFilter(RowFilter.ComparisonType.AFTER, fecha1,0));
        f2.add(RowFilter.dateFilter(RowFilter.ComparisonType.EQUAL, fecha2,0));
        f2.add(RowFilter.dateFilter(RowFilter.ComparisonType.BEFORE, fecha2,0));
        finalf.add(RowFilter.orFilter(f1));
        finalf.add(RowFilter.orFilter(f2));
        finalf.add(RowFilter.regexFilter("(?i)"+Filtro.getText()));
        //finalf.add(RowFilter.regexFilter(Filtro.getText(),1));
        filtroAnd.setRowFilter(RowFilter.andFilter(finalf));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFilPedidos = new javax.swing.JTable();
        Aceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ChekFecha = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FechaInicial = new javax.swing.JFormattedTextField(new Date());
        FechaFinal = new javax.swing.JFormattedTextField(new Date());
        Filtro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PEDIDOS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel1.setText("PEDIDOS");

        try{
            TablaFilPedidos.setModel(Conector.getInstance().buildTableModel("SELECT pedido.id, pedido.fecha,cliente.nombre,pedido.concepto,pedido.abonoTotal,pedido.total,cliente.telefono FROM pedido JOIN cliente ON pedido.idCliente=cliente.id",cols));
        } catch(SQLException ex){
        }
        TablaFilPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaFilPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFilPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFilPedidos);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtrar:");

        ChekFecha.setText("Filtrar por Fecha");
        ChekFecha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ChekFechaStateChanged(evt);
            }
        });

        jLabel3.setText("Fecha Inicial:");

        jLabel4.setText("Fecha Final:");

        FechaInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        FechaFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FiltroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(ChekFecha)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChekFecha)
                    .addComponent(FechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        dispose();
        FiltroPedidos.instancia=null;
        folio=TablaFilPedidos.getValueAt(row,0).toString();
        if(TablaFilPedidos.getValueAt(row,2)==null) {
            nombre=" ";
        }
        else {
            nombre=TablaFilPedidos.getValueAt(row,2).toString();
        }
        if(TablaFilPedidos.getValueAt(row,1)==null) {
            fecha=" ";
        }
        else {
            fecha=TablaFilPedidos.getValueAt(row,1).toString();
        }
        if (TablaFilPedidos.getValueAt(row,5)==null) {
            total=" ";
        }
        else {
            total=TablaFilPedidos.getValueAt(row,5).toString();
        }
        if (TablaFilPedidos.getValueAt(row,4)==null) {
            abono=" ";
        }
        else {
            abono=TablaFilPedidos.getValueAt(row,4).toString();
        }
        if(TablaFilPedidos.getValueAt(row,3)==null){
            concepto=" ";
        }
        else {
            concepto=TablaFilPedidos.getValueAt(row,3).toString();
        }
        if("CancelarPedido".equals(clase_procedencia))
            CancelarPedido.getInstance().setear(folio,nombre,fecha,total,abono,concepto);
        if("Abonar".equals(clase_procedencia))
            Abono.getInstance().setear(folio,nombre,total,abono,fecha,concepto);
        
        dispose();
        FiltroPedidos.instancia=null;
    }//GEN-LAST:event_AceptarActionPerformed

    private void TablaFilPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFilPedidosMouseClicked
        row = TablaFilPedidos.rowAtPoint(evt.getPoint());
        if(evt.getClickCount()==2) {
        row = TablaFilPedidos.rowAtPoint(evt.getPoint());
        folio=TablaFilPedidos.getValueAt(row,0).toString();
        nombre=TablaFilPedidos.getValueAt(row,2).toString();
        fecha=TablaFilPedidos.getValueAt(row,1).toString();
        concepto=TablaFilPedidos.getValueAt(row,3).toString();
        total=TablaFilPedidos.getValueAt(row,5).toString();
        abono=TablaFilPedidos.getValueAt(row,4).toString();
        if(clase_procedencia=="CancelarPedido")
            CancelarPedido.getInstance().setear(folio,nombre,fecha,total,abono,concepto);
        if(clase_procedencia=="Abonar")
            Abono.getInstance().setear(folio,nombre,total,abono,fecha,concepto);
        
        dispose();
        FiltroPedidos.instancia=null;
        }
    }//GEN-LAST:event_TablaFilPedidosMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();
        FiltroPedidos.instancia=null;
    }//GEN-LAST:event_formWindowClosed

    private void ChekFechaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ChekFechaStateChanged
        checarFiltros();
    }//GEN-LAST:event_ChekFechaStateChanged

    private void FiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FiltroKeyPressed
        checarFiltros();
    }//GEN-LAST:event_FiltroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiltroPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Aceptar;
    public javax.swing.JCheckBox ChekFecha;
    public javax.swing.JFormattedTextField FechaFinal;
    public javax.swing.JFormattedTextField FechaInicial;
    public javax.swing.JTextField Filtro;
    public javax.swing.JTable TablaFilPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
